// Centralized insurance list and ordering-provider mapping
// Use this list to populate insurance dropdowns across the app.

export const STATES_AND_TERRITORIES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
];

export const NATIONAL_INSURERS = [
  "Aetna",
  "Anthem",
  "Blue Cross Blue Shield Association",
  "Cigna",
  "UnitedHealthcare",
  "Humana",
  "Kaiser Permanente",
  "Centene",
  "Molina Healthcare",
  "WellCare",
  "Ambetter",
  "Oscar Health",
  "Bright Health",
  "Health Care Service Corporation (HCSC)",
  "CareSource",
  "Magellan Health",
  "Highmark",
  "Independence Blue Cross",
  "Tufts Health Plan",
  "Harvard Pilgrim Health Care",
  "EmblemHealth",
  "Geisinger Health Plan",
  "UPMC Health Plan",
  "Priority Health",
  "Medica",
  "Blue Shield of California",
  "Tricare",
  "VA (Veterans Affairs)",
  "Medicaid",
  "Medicare",
  "Medicare Advantage",
  "Other / Self-pay",
];

// Build a comprehensive insurers array combining national payers and
// state-specific Blue Cross Blue Shield entries.
const _UNSORTED_INSURERS: string[] = [
  ...NATIONAL_INSURERS,
  // Add state-specific Blue Cross Blue Shield entries
  ...STATES_AND_TERRITORIES.map((s) => `Blue Cross Blue Shield of ${s}`),
  // Add some commonly used regional plan names not captured above
  "Florida Blue",
  "Hawaii Medical Service Association (HMSA)",
  "Horizon Blue Cross Blue Shield of New Jersey",
  "Excellus BlueCross BlueShield",
  "Blue Cross Blue Shield of Texas (BCBSTX)",
  "Regence BlueCross BlueShield",
  "HealthPartners",
  "Wellmark",
  "Medical Mutual",
  "Community Health Choice",
  "Mercy Health Plan",
];

export const INSURERS: string[] = _UNSORTED_INSURERS
  .slice()
  .sort((a, b) => a.localeCompare(b));

export default INSURERS;
